### ISSUE TITLE
How to specify the order in which fields should be displayed ?

### ISSUE THREAD

**Issue by lei12** [stefanofontanelli/ColanderAlchemy#45]
form.render() keeps returning fields in the initial order of the mapping, skipping the includes list order : is there a way to customize this ?

    class Model(DeclarativeBase):
        __tablename__ = 'model_table'
        id = Column(...)
        col1 = Column(...)
        col2 = Column(...)
        col3 = Column(...)

    schema = SQLAlchemySchemaNode(Model, includes=['col3','col2','col1'])

=> keeps displaying col1 then col2 then col3 fields

**Comment by tisdall** [comment]
A really poorly named PR was added that now allows you to control the order of schema element via the `include` argument.  Sorry for the extremely long wait!
