### ISSUE TITLE
Need a new version release (0.3.2)

### ISSUE THREAD

**Issue by uralbash** [stefanofontanelli/ColanderAlchemy#77]
What must be done to release a new version? Maybe I can solve some problems. This blocks the release of  sacrud_deform package and all that depends on it.

**Comment by tisdall** [comment]
Yeah, I was in the middle doing that when I had my second child arrive a week early..  ;)

I'd like to merge #62 and #75, give people a little time to test everything out, and then push out a new release.

**Comment by tisdall** [comment]
okay, #62 is merged in and #75 has been updated to be merged easily.  @uralbash can you test out #75 with what you're doing in sacrud_deform?  The changes I made there are to help handle deform a bit better.  I'd like to make sure I'm not breaking things on people, though.

**Comment by uralbash** [comment]
Well, I will try to explore the changes in #75 and see how it affects the `sacrud_deform`. I hope that everything will work :smiley:

**Comment by uralbash** [comment]
I tested `pyramid_sacrud` with `sacrud_deform` based on `colanderalchemy` from this branch https://github.com/tisdall/ColanderAlchemy/tree/nullable

And got the following results:

* [**Works!**] make the missing value for nullable fields be "null" instead of drop
* [**Works!**]  `dictify()` should return appstructs with `colander.null` in the appropriate spots
* [**I'm not used it**] `objectify()` should handle `colander.null` as `None`

In my case, everything works!

**Comment by elemoine** [comment]
@tisdall Is there anything we can do to make the 0.3.2 release happen?

**Comment by tisdall** [comment]
@elemoine I wanted to include #75 but I still need to update the docs for that PR.  I'll see if I can find some time today...

**Comment by tisdall** [comment]
okay, I pushed the version up!  Hopefully there's no issues.

**Comment by elemoine** [comment]
Cool. Thanks. I'll test it in our application. Good work on ColanderAlchemy, it really does the job for us!

**Comment by uralbash** [comment]
Thank you so much. This greatly simplifies my job. But I can not install it from pypi.
```bash
$ pip install colanderalchemy==0.3.2
Collecting colanderalchemy==0.3.2
  Could not find a version that satisfies the requirement colanderalchemy==0.3.2 (from versions: 0.1.0a0, 0.1b0, 0.1b2, 0.1b3, 0.1b4, 0.1b5, 0.1b6, 0.2a1, 0.2b1, 0.2b2, 0.2.0, 0.3.0, 0.3.1)
  No distributions matching the version for colanderalchemy==0.3.2
```

**Comment by elemoine** [comment]
Same problem here. I don't see version 3.2.0 in https://pypi.python.org/simple/colanderalchemy/.

**Comment by tisdall** [comment]
I'll take a look...  I did "python setup.py register" to upload it...  I'm not sure what else needs to be done to complete it.  :(

**Comment by elemoine** [comment]
`register` is not sufficient, you also need to `upload` the package.

**Comment by tisdall** [comment]
@elemoine ^_^  yeah, I just figured that out.  I then accidentally uploaded the file to the wrong spot, deleted it, and now it won't let me re-upload it...  I'm creating a .post1 release to fix that.  So annoying!

**Comment by uralbash** [comment]
Yet there is no version with files on pypi, you can manually delete this release and reloaded again.

**Comment by tisdall** [comment]
@uralbash - http://sourceforge.net/p/pypi/support-requests/468/    They prevent you from re-uploading any new file with the same name as a previous on due to caching issues.  It makes it annoying if you make any little mistake.

There's now a 0.3.2.post1 version on there ready to go!

**Comment by uralbash** [comment]
It works! Thank you! Perhaps I should close the task.
