### ISSUE TITLE
Handling JSON/JSONB columns

### ISSUE THREAD

**Issue by miohtama** [stefanofontanelli/ColanderAlchemy#85]
Currently I am having some types in my models which are JSON/JSONB (PostgreSQL). The default `get_schema_from_column` cannot handle them. The optimal mapping for these columns, unless user-given override is in place, should be read only string.

Would be be interested to cover this case in ColanderAlchemy core or should I keep it separate and maybe provide documentation how to handle the situation?

**Comment by tisdall** [comment]
We could add that as a default, that's no problem...  I had thought about just defaulting to a plain text-input for everything that we didn't have something more specific for.

What's the rational behind making it a read-only field, though?

**Comment by miohtama** [comment]
Only sense it to make it read-only field only, is that Colander itself (might) not have native JSON field yet. So entering a typo in the input, which is quite easy with JSON, causes the database to reject the transaction and this leads to 500 error. 

Note to self: Check for Colander field/Deform widget to edit JSON.

**Comment by tisdall** [comment]
Unfortunately there's no sort of default handling of JSON in deform...  I guess someone could create a widget, but editing JSON is very much a programmer thing and not really a web user thing.  If you have JSON, you really need to create your own widget that deals with the specific kind of data you're storing in the JSON field.

I was thinking more of the base case (not just JSON) for all field types that we don't recognize in ColanderAlchemy becoming a simple text field.  However, you're right, some types will likely fail when they're resubmitted and they try to store them back into the database.  JSON should work provided it's formatted correctly, but other types may not be able to properly handle a string formatted version.

Really, though, JSON needs to be handled by the developer... it's kind of beyond what ColanderAlchemy can reasonably do anything about.

**Comment by miohtama** [comment]
Which brings another point - how to extend ColanderAlchemy to handle this? What I did is that I subclasses `SQLAlchemySchemaNode` and added in all special cases, as I found this is was the easiest way to do it? But there are probably other ways? 

Is there a way to pass around column mappings and type overrides easily?

**Comment by tisdall** [comment]
how about: https://github.com/stefanofontanelli/ColanderAlchemy/issues/66#issuecomment-78124816

**Comment by miohtama** [comment]
The problem is this approach that you are putting form-related (UI) stuff in the models (data) (though just hints) - and at the end of this road is something horrible, as, for example, you start cross-import between UI and models.  Thus, I'd like to maintain separation between the form hints and the actual SQLAlchemy model.

Also the hint syntax in model is quite heavy, but this is more of a problem with Python itself.

**Comment by miohtama** [comment]
Is it ok if I present an alternative way to make type hinting as a pull request? Like using subclasses or giving some mapping parameters or mapping fuctions for SQLAlchemySchemaNode?

**Comment by tisdall** [comment]
yeah, I'm open to suggestions.

However, the whole concept of ColanderAlchemy means there's a close coupling between the SqlAlchemy object and the end rendering in deform.  How myself (and at least one other person I know :wink: ) deals with limitations in ColanderAlchemy is to generate a colander schema with ColanderAlchemy and then modify the result afterwards to suit needs.  So, you'd call `SQLAlchemySchemaNode` on your class and exclude the JSON field (as that will cause an exception) and then modify the resulting schema into what you actually want.

Another solution is to use the `overrides` argument to `SQLAlchemySchemaNode` to specify a colander type.

**Comment by miohtama** [comment]
Cool. Give me some days and I'll think about the strategy :)

On 6 May 2015 at 19:10, Tim Tisdall <notifications@github.com> wrote:

> yeah, I'm open to suggestions.
>
> However, the whole concept of ColanderAlchemy means there's a close
> coupling between the SqlAlchemy object and the end rendering in deform. How
> myself (and at least one other person I know [image: :wink:] ) deals with
> limitations in ColanderAlchemy is to generate a colander schema with
> ColanderAlchemy and then modify the result afterwards to suit needs. So,
> you'd call SQLAlchemySchemaNode on your class and exclude the JSON field
> (as that will cause an exception) and then modify the resulting schema into
> what you actually want.
>
> Another solution is to use the overrides argument to SQLAlchemySchemaNode
> to specify a colander type.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stefanofontanelli/ColanderAlchemy/issues/85#issuecomment-99525364>
> .
>



-- 
Mikko Ohtamaa
http://opensourcehacker.com
http://twitter.com/moo9000

**Comment by pieterproigia** [comment]
I'd fix this by defining a new sqlalchemy type, and using https://github.com/stefanofontanelli/ColanderAlchemy/pull/62:

```python
"""Defines SqlAlchemy types and other objects needed in _base."""
import collections
import json

import colander
from sqlalchemy.dialects import postgresql
from sqlalchemy import types


class JSONType(object):

    """Colander type which is able to serialize and deserialize JSON."""

    def serialize(self, node, appstruct):
        """Serialize JSON."""
        if appstruct is colander.null:
            return colander.null
        try:
            return json.dumps(appstruct)
        except Exception as e:
            raise colander.Invalid(node,
                                   '%s cannot be serialized: %s'
                                   % (appstruct, e))

    def deserialize(self, node, cstruct):
        """Deserialize JSON."""
        if cstruct is colander.null:
            return colander.null
        try:
            # use OrderedDict as order is important for us.
            return json.loads(cstruct,
                              object_pairs_hook=collections.OrderedDict)
        except Exception as e:
            raise colander.Invalid(node,
                                   '%s is not a JSON object: %s'
                                   % (cstruct, e))

    def cstruct_children(self, node, cstruct):
        """Used to determine the children of this type.

        As deserializing JSON also makes sure the children are correct
        we do not use this system.
        """
        return []


class JSON(types.TypeDecorator):

    """Copy of the postgresql.JSON type, with colanderalchemy config."""

    impl = postgresql.JSON

    __colanderalchemy_config__ = {'typ': JSONType}
```

Now I use the new `JSON` class where I want to be able to deserialize it.
Reuse the code at harts content if you want.

**Comment by tisdall** [comment]
@pieterproigia thanks for that!  You don't _have_ to use #62, though, you could also:
```python
    json_info = Column(
        postgresql.JSON(),
        info={ 'colanderalchemy': {
            'typ': JSONType
        }
    )
```

**Comment by pieterproigia** [comment]
@tisdall You're totally right! But as @miohtama mentioned in https://github.com/stefanofontanelli/ColanderAlchemy/issues/85#issuecomment-99510493 that he did not want it in his models code, then using a new `JSON` column type might be a solution.

**Comment by miohtama** [comment]
Hey @pieterproigia - this looks like less intrusive solutions! A step to right direction. 

Though to nitpick I am scared how `types.TypeDecorator` works on import time and has some magic there, you don't explicitly tell SQLAlchemy to use, but that's more an issue with SQLAlchemy itself.

Closing this now.

**Comment by tisdall** [comment]
@miohtama I'm not sure I understand what you're saying...  You define a new `JSON` type using the `TypeDecorator` and then in your SQLAlchemy object declarations you use that `JSON` type now and not the `postgresql.JSON`.  The new `JSON` is essentially a wrapper with the ColanderAlchemy configuration in it.
