### ISSUE TITLE
CheckedPassword widget from deform library always fails

### ISSUE THREAD

**Issue by mariano-ramon** [stefanofontanelli/ColanderAlchemy#94]
It works creating the Colander Schema directly, but not from ColanderAlchemy, I need to create it this way (replacing the field) because I dont want that widget in the login form, just the the register

`
class User(Base, UserMixin):
    __tablename__ = 'usertable'
    id = Column(Integer, primary_key=True)
    username = Column(String(80))
    usermail = Column(String(80))
    password = Column(String(80))

    def __init__(self, username, password):
        self.username = username
        self.usermail = usermail
        self.password = password

password = SchemaNode(
                ColanderString(),
                validator=Length(min=5),
                widget=widget.CheckedPasswordWidget(redisplay=True),
                description='Type your password and confirm it')

userschemareg = SQLAlchemySchemaNode(User, excludes=['id', 'password'],
                              includes=['username', 'usermail', password ],
                              title='Login')
`

**Comment by mariano-ramon** [comment]
sorry I was missing the name parameter when creating the SchemaNode

**Comment by tisdall** [comment]
so..  it's all good?  I can close this issue?

**Comment by mariano-ramon** [comment]
Yes, sir. Sorry for the time.

**Comment by tisdall** [comment]
;)  no worries!
